services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-ps
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-ntk

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    container_name: mysql_ps
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notes-app-ntk

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_cont
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - notes-app-ntk
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"

volumes:
  mysql-data:

networks:
  notes-app-ntk:
    driver: bridge
    name: notes-app-network
