kind: Deployment
apiVersion: apps/v1
metadata:
  name: note-app-deployment
  namespace: note-app-ns
  labels:
    app: note-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app

  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-app-container
        image: gendocker314/notes-app-k8s:latest
        ports:
        - containerPort: 8000
