kind: Service
apiVersion: v1
metadata:
  name:  note-app-service
  namespace: note-app-ns

spec:
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
